spring.application.name=multi-skill-agent


# Anthropic
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.model=claude-haiku-4-5-20251001

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/assistant_db
spring.datasource.username=assistant_user
spring.datasource.password=assistantuserpassword
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
